apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: analytics-service
    app.kubernetes.io/part-of: helep
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8005"
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - name: http
      port: 8005
      targetPort: 8005
      protocol: TCP
