apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dispatch-service-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: dispatch-service
    app.kubernetes.io/part-of: helep
data:
  KAFKA_BOOTSTRAP: {{ .Values.kafkaBootstrap | default .Values.global.kafkaBootstrap | quote }}
  MATCHER: {{ .Values.matcherStrategy | default .Values.global.matcherStrategy | default "nearest" | quote }}
  SERVICE_PORT: "8003"
  DB_PATH: "/data/dispatch.db"
