apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sos-service-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: sos-service
    app.kubernetes.io/part-of: helep
data:
  KAFKA_BOOTSTRAP: {{ .Values.kafkaBootstrap | default .Values.global.kafkaBootstrap | quote }}
  MATCHER: {{ .Values.matcherStrategy | default .Values.global.matcherStrategy | default "nearest" | quote }}
  SERVICE_PORT: "8002"
  DB_PATH: "/data/sos.db"
